# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'tty-prompt', '~> 0.23.0'

gem 'artii', '~> 2.1', '>= 2.1.2'

gem 'json', '~> 2.5', '>= 2.5.1'

gem 'rainbow', '~> 3.0'

